-- packages/db/migrations/0009_app_config.sql
-- Auxiliary app_config key-value table for runtime feature flags.
-- Applied manually on VPS via psql; not generated by drizzle-kit since
-- it's auxiliary infrastructure (not in the schema graph).

CREATE TABLE IF NOT EXISTS public.app_config (
  key text PRIMARY KEY,
  value text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS app_config_public_read ON public.app_config;
CREATE POLICY app_config_public_read ON public.app_config
  FOR SELECT USING (true);

-- No INSERT/UPDATE policy: service role only.
